export const FETCH_USER_SUMMARY = "FETCH_USER_SUMMARY";
export const FETCH_USER_SUMMARY_ASYNC = "FETCH_USER_SUMMARY_ASYNC";
export const FETCH_ORDER_SUMMARY = "FETCH_ORDER_SUMMARY";
export const FETCH_ORDER_SUMMARY_ASYNC = "FETCH_ORDER_SUMMARY_ASYNC";
export const TOGGLE_ORDER_BTN = "TOGGLE_ORDER_BTN";
export const SET_ORDER_NAV = "SET_ORDER_NAV";

export const START_FETCHING = "START_FETCHING";
export const END_FETCHING = "END_FETCHING";
export const ERROR_EXIST = "ERROR_EXIST";
